# Generated by Django 4.1.4 on 2022-12-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.clubs'),
        ),
    ]
