# Generated by Django 4.1.4 on 2022-12-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_slug_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
    ]
