# Generated by Django 4.1.4 on 2023-01-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_about_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='upload profile image:'),
        ),
    ]
